export const catalogo = [ 
    { 
        codProduto: 1,
        descricaoProduto:"Cada par de brincos pequenos é habilmente trabalhado com atenção aos detalhes, exibindo uma simplicidade que é verdadeiramente encantadora. O tamanho compacto dos brincos os torna adequados para todas as idades, estilos e ocasiões. Eles complementam tanto visuais casuais quanto formais.",
        precoProduto: 59.99, 
        nomeProduto: "Brinco Flor Rosa Banho de Ouro 18k", 
        imagemProduto: "../img/brinco_01.png",
        mostrarNaHome: true,
        categoria:"brinco",
    },       
    { 
        codProduto: 2,
        descricaoProduto:"Cada par de brincos pequenos é habilmente trabalhado com atenção aos detalhes, exibindo uma simplicidade que é verdadeiramente encantadora.O tamanho compacto dos brincos os torna adequados para todas as idades, estilos e ocasiões. Eles complementam tanto visuais casuais quanto formais.",
        precoProduto: 59.99, 
        nomeProduto: "Mini Argola Dupla", 
        imagemProduto: "../img/brinco_02.png", 
        mostrarNaHome: false,
        categoria:"brinco",
    },    
    { 
        codProduto: 3,
        descricaoProduto:"Estes brincos pequenos são a definição da elegância discreta.Com seu design minimalista e tamanho delicado, eles são perfeitos para quem busca um toque de sofisticação sem excessos.",
        precoProduto: 49.99, 
        nomeProduto: "Brincos de Mini argola de Coração", 
        imagemProduto: "../img/brinco_03.png", 
        mostrarNaHome: false,
        categoria:"brinco",
    }, 
    { 
        codProduto: 4,
        descricaoProduto:"Mostre seu amor com este colar de coração. Feito com materiais de alta qualidade, é um presente perfeito para aqueles que ocupam um lugar especial em seu coração.",
        precoProduto: 99.99, 
        nomeProduto: "Colar de Coração Liso Ouro Branco", 
        imagemProduto: "../img/colar_01.png",  
        mostrarNaHome: true,
        categoria:"colar",
    },     
    { 
        codProduto: 5,
        descricaoProduto:"Deixe o sol brilhar eternamente em sua vida com o nosso deslumbrante Relicário de Sol. Esta joia única é mais do que apenas um acessório; é um símbolo de esperança, alegria e renovação. O reluzente medalhão de sol, cuidadosamente esculpido em detalhes vívidos, captura a energia e a vitalidade do astro-rei",
        precoProduto: 120.90, 
        nomeProduto: "Relicário Círculo Sol Banho de Ouro 18k", 
        imagemProduto: "../img/colar_02.png", 
        mostrarNaHome: false,
        categoria:"colar",
    },     
    { 
        codProduto: 6,
        descricaoProduto:"Elegância minimalista define este colar. Sua simplicidade é sua força, e pode ser usado sozinho ou combinado com outros colares para um visual personalizado. Uma escolha versátil para quem busca estilo discreto.",
        precoProduto: 89.90, 
        nomeProduto: "Colar de Elos Entrelaçados", 
        imagemProduto: "../img/colar_03.png", 
        mostrarNaHome: false,
        categoria:"colar",
    },    
    { 
        codProduto: 7,
        descricaoProduto:"Este deslumbrante conjunto de brinco e colar é uma expressão perfeita de beleza e harmonia. Cada peça é cuidadosamente projetada para complementar a outra, criando um conjunto que emana sofisticação e estilo.",
        precoProduto: 159.90, 
        nomeProduto: "Conjunto Oval Zircônia Roxa e Incolor", 
        imagemProduto: "../img/conjunto_01.png", 
        mostrarNaHome: false,
        categoria:"conjunto",
    },     
    { 
        codProduto: 8,
        descricaoProduto:"O conjunto de brinco e colar é o complemento perfeito para ocasiões especiais, desde festas sofisticadas até casamentos memoráveis. Ele adiciona um brilho irresistível ao seu visual.",
        precoProduto: 159.90, 
        nomeProduto: "Conjunto Gota Morganite Entorno Incolor", 
        imagemProduto: "../img/conjunto_02.png", 
        mostrarNaHome: false,
        categoria:"conjunto",
    },     
    { 
        codProduto: 9,
        descricaoProduto:"Celebre a beleza e a elegância com este conjunto de brinco e colar. É uma obra-prima que não apenas aprimora seu estilo, mas também conta uma história de sofisticação e requinte. Adquira este conjunto hoje e adicione um toque de luxo à sua vida e ao seu visual.",
        precoProduto: 159.00, 
        nomeProduto: "Conjunto Oval Zircônia Esmeralda", 
        imagemProduto: "../img/conjunto_03.png", 
        mostrarNaHome: true,
        categoria:"conjunto",
    },] 
    
